
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/client_schedule_test
    username: "rob"
    password: "mobius42"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
